services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Application\Port\Cli\SendMercureNotification:
        arguments:
            $baseUrl: '%env(resolve:SERVER_NAME)%'
    App\Application\Port\Controller\ProductController:
        tags: ['controller.service_arguments']
    App\Application\CommandHandler\CreateProductHandler: ~
