parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Port\Cli\SendMercureNotification:
        arguments:
            $baseUrl: '%env(resolve:SERVER_NAME)%'
    App\Port\Controller\ProductController:
        tags: ['controller.service_arguments']
